import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyHeader from "./ui/header";
import MyFooter from "./ui/footer";
import "@/style/globals.scss";
import { ThemeProvider } from "./theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rocky Blog",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="w-full h-full">
            <MyHeader />
            <main className="w-full max-w-screen-xl px-4 mx-auto mt-4 mb-12">
              {children}
            </main>
            <MyFooter />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
