import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyHeader from "./ui/header";
import MyFooter from "./ui/footer";
import "@/style/globals.scss";
import { ThemeProvider } from "./theme-provider";
import { Providers } from "./redux/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rocky Blog",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <div className="w-screen h-screen flex flex-col">
              <MyHeader className="flex-none" />
              <div className="w-full mx-auto mt-4 flex-1">
                <main className="w-full min-h-full h-auto max-w-screen-xl mx-auto">
                  {children}
                </main>
                <MyFooter className="flex-none" />
              </div>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
